### ISSUE TITLE
add newline to radio boxes

### ISSUE THREAD

**Issue by alexdecastro** [ABCD-STUDY/ABCDreport#1]
No newline after each radio button label. Expected behavior is to have consistent label, entry field setup on the page for all fields.

**Comment by alexdecastro** [comment]
suggested fix is a newline after the label (should fix issue in e0293eb7e6be52c3f8377598ded55fd678889372)

**Comment by alexdecastro** [comment]
fixed by adding a newline after the label (fixed in 8e59e2edc272dff4ed6b85497bcb83f47cfcd0d0)

**Comment by HaukeBartsch** [comment]
tested and works as expected
